### ISSUE TITLE
no horizontal separators when Tableize-ing csv file

### ISSUE THREAD

**Issue by githorse** [dhruvasagar/vim-table-mode#109]
When I call `Tableize` on

```
foo,bar
foo,bar
```

I get:

```
| foo | bar |
| foo | bar |
```

How can I get the horizontal separators between each line?

**Comment by dhruvasagar** [comment]
You would have to add those manually.

**Comment by roneyrao** [comment]
Why not add them automatically?

**Comment by dhruvasagar** [comment]
Well I think there's a valid case for this, I am willing to add support for a separate configuration to enable automatic border creation perhaps and when that is enabled, `:Tableize` would automatically add borders between each line. But then, it would also add borders when you manually add a row to the table.

The reason auto  border creation was removed was because it was less desirable, borders are typically more useful for separating header values, and much less for row separation, it's just wasted lines for some aesthetics, but I do see some value in that being something one can enable via an option.

**Comment by ScrumpyJack** [comment]
+1 for this feature. I would use it to create a markdown table

**Comment by dhruvasagar** [comment]
@ScrumpyJack @githorse I have pushed an update with a new option `g:table_mode_tableize_auto_border` that allows you to enable automatic border creation for tables when using Tableize. Note, this is only applicable to Tableize since it feels jarring and error prone when editing tables with Table Mode enabled.
