### ISSUE TITLE
Isn't automatically drawing horizontal line

### ISSUE THREAD

**Issue by snoblenet** [dhruvasagar/vim-table-mode#116]
I am hoping to use `vim-table-mode` to create `grid tables` as defined by Pandoc's markdown format.

My `vimrc` includes:

```
Plugin 'dhruvasagar/vim-table-mode'
  let g:table_mode_corner_corner='+'
  let g:table_mode_header_fillchar='='
```

In insert mode with table mode enabled, I type: `|Task|Shortcut|<carriage return>||<carriage return>`.

I expect it to result in something like:

```
| Task  |  Shortcut |
+=======+===========+
```

Instead I get:

```
| Task | Shortcut |
|      |          |
|
```

Can you advise?

Many thanks.

**Comment by dhruvasagar** [comment]
Hi,

You should see something like this : 

```
| Task | Shortcut |
+------+----------+
|
```

Until you add the second separator / content in the cell. However once you do that, you should see : 

```
| Task | Shortcut |
+======+==========+
|      |          |
```

**Comment by dhruvasagar** [comment]
Also, in order for you to add the border line you should add `||` on a new line without any spaces, that gets converted to a border line.

The above described glitch happens because of the way I distinguish whether or not it is a header border (must be immediately after a row and followed by at least one more row).

**Comment by dhruvasagar** [comment]
Let me know if you're still facing an issue

**Comment by snoblenet** [comment]
sorry -- all good
