### ISSUE TITLE
how to merge multiple columns?

### ISSUE THREAD

**Issue by D1mon** [dhruvasagar/vim-table-mode#129]
```
| name            | address                  | phone                         |
|-----------------+--------------------------+-------------------------------|
| John Adams      | 1600 Pennsylvania Avenue | 0123456789                    |
|-----------------+--------------------------+-------------------------------|
|              221B Baker Street             | 0987654321                    |
|-----------------+--------------------------+-------------------------------|
```

Example:
I combined "name" and "address" in the second line(row). How can I do that?

|  | 221B Baker Street        | 0987654321 |

You can put "|", but then you get 3 columns, but you need to somehow do it so that there are 2 columns (one combined).

**Comment by dhruvasagar** [comment]
This is a highly requested, but unimplemented feature. It's just hard to do it neatly without adding some meta info within the table to signify the merging of cells. I am still not a 100% convinced if this should really be implemented since it isn't exactly aligned with the goals of this plugin. However I am open to PRs and may try some strategies in near future myself since this has been a highly requested feature.

**Comment by D1mon** [comment]
Yes, you can try it. This is really a very useful feature.

**Comment by dhruvasagar** [comment]
Closing this, will update #18 if there's any update on this.
