### ISSUE TITLE
unexpected internal seperator in horizontal line for markdown

### ISSUE THREAD

**Issue by nathanbraun** [dhruvasagar/vim-table-mode#142]
Hi there, I'm trying to use this plugin with pandoc, and so I have the following options on:

let g:table_mode_header_fillchar='='
let g:table_mode_corner_corner='+'

When I enter a table in a markdown file I see (note the |'s on all the internal linebreaks):

```
+------|-----|-----------------+
| name | age | address         |
+======|=====|=================+
| joe  | 20  | 123 main street |
+------|-----|-----------------+
| john | 30  | 987 fake road   |
+------|-----|-----------------+
```

Vs what I want, and see when I do it in a regular text file:

```
+------+-----+-----------------+
| name | age | address         |
+======+=====+=================+
| joe  | 20  | 123 main street |
+------+-----+-----------------+
| john | 30  | 987 fake road   |
+------+-----+-----------------+
```

Any idea what's going on?  Just started with this plugin so I could def be missing something too.  Thanks!

**Comment by nathanbraun** [comment]
I figured it out, table_mode_corner wasn't set properly even though I put it in my vimrc.  I fixed it by adding a file to change it after/ftplugin directory.

**Comment by kaymmm** [comment]
@nathanbraun Can you explain your fix please? I'm encountering the same issue. I'm setting the correct value in my vimrc, however the plugin seems to be resetting the value to `|` after the fact according to my log file. I'm not sure if this is a problem with vim-plug, my vimrc, or this plugin, but it's annoying. FWIW, Vim-plug should be loading this plugin at startup since I'm not doing any fancy conditional loading or anything. 

I can cheat by using an autocmd to reset `table_mode_corner`, but that's hacky and this bug seems like it might actually be an issue with the plugin itself and how it's setting variables.

**Comment by nathanbraun** [comment]
My solution is sort of hacky too.  I'm using neovim, and what worked for me was to create the file:

~/.config/nvim/after/ftplugin/pandoc.vim
(my understanding with regular vim is that this would be  ~/.vim/ftplugin/pandoc.vim, but I haven't tested it)

with just the one line:

let g:table_mode_corner='+'

**Comment by dhruvasagar** [comment]
There are 2 separate settings `g:table_mode_corner` and `g:table_mode_corner_corner`, you need to set both for this I believe. Refer to `:help table-mode-corner` and `:help table-mode-corner-corner` for details

**Comment by dhruvasagar** [comment]
There's an `ftplugin/markdown.vim` that adds a setting `let b:table_mode_corner='|'`, this came from a PR.  I believe this is the right setting based on gfm spec.

**Comment by kaymmm** [comment]
@dhruvasagar you just solved the issue with the markdown.vim corner setting (I was already setting both `corner` and `corner_corner`). The problem is that markdown files can also be used with Pandoc, which allows for `+` grid tables but dislikes certain types of pipe tables. 

I can see the potential benefit of setting the value on a per-filetype basis, but maybe that should be modifiable through a separate setting. A record holding filetypes and corresponding settings for each variable seems a bit heavy, but at least it wouldn't break functionality like the current method. Alternatively, separate variables for md files wouldn't be the worst thing. 

The current method assumes a per-filetype setting without allowing users to change the default behavior without using a hacky workaround. Without reverting the previous PR, this default behavior should be documented in the readme and documentation with a possible workaround such as:
`autocmd BufRead,BufFilePre,BufNewFile *.md let g:table_mode_corner='+'`

I'll take a look at the PR to see if maybe there is some other more elegant workaround for this as well.

**Comment by TimmFitschen** [comment]
Work-around with (non-neo-)vim version Gentoo-8-0-1298: Add a `pandoc` filetype plugin and set the *per-buffer* variables like this:

```bash
    $ cat ~/.vim/ftplugin/pandoc.vim 
    let b:table_mode_corner="+"
    let b:table_mode_corner_corner="+"
    let b:table_mode_header_fillchar="="
```

thanks to @nathanbraun

**Comment by dhruvasagar** [comment]
> @dhruvasagar you just solved the issue with the markdown.vim corner setting (I was already setting both `corner` and `corner_corner`). The problem is that markdown files can also be used with Pandoc, which allows for `+` grid tables but dislikes certain types of pipe tables.
> 
> I can see the potential benefit of setting the value on a per-filetype basis, but maybe that should be modifiable through a separate setting. A record holding filetypes and corresponding settings for each variable seems a bit heavy, but at least it wouldn't break functionality like the current method. Alternatively, separate variables for md files wouldn't be the worst thing.
> 
> The current method assumes a per-filetype setting without allowing users to change the default behavior without using a hacky workaround. Without reverting the previous PR, this default behavior should be documented in the readme and documentation with a possible workaround such as:
> `autocmd BufRead,BufFilePre,BufNewFile *.md let g:table_mode_corner='+'`
> 
> I'll take a look at the PR to see if maybe there is some other more elegant workaround for this as well.

The elegant workaround for this, like suggested by @nathanbraun, is to do it in an `after/ftplugin/markdown.vim` that will override these markdown settings added by our ftplugin. I think that's a reasonable approach.
