### ISSUE TITLE
ftplugins solve rule?

### ISSUE THREAD

**Issue by tsuyoshicho** [dhruvasagar/vim-table-mode#166]
Currently

```
$> vim-table-mode/ftplugin/
markdown_tablemode.vim
rst_tablemode.vim
```

To correct work change below?

```
$> vim-table-mode/ftplugin/
markdown/tablemode.vim
rst/tablemode.vim
```

I knows that vim search and load rule are `<plugin>.vim` and `<plugin>/*.vim`

**Comment by dhruvasagar** [comment]
@tsuyoshicho If you check `:h ftplugin-name` you'll see that `<plugin>_text.vim` is also a supported format, I used that to avoid having unnecessary folders, since we only have 2 ftplugins for the time being, it's more convenient to manage them all in a single place.

Is there an actual issue you're facing ?

**Comment by tsuyoshicho** [comment]
oh sorry

**Comment by dhruvasagar** [comment]
@tsuyoshicho No worries, glad to help.
