### ISSUE TITLE
Setting corners not applied correctly

### ISSUE THREAD

**Issue by eliedrian** [dhruvasagar/vim-table-mode#185]
Setting corners and headers like so in vimrc:

```
let g:table_mode_corner_corner='+'
let g:table_mode_header_fillchar='='
```
is not applied thoroughly.

Editing a `*.md` file will result in a mix of '+' and '|' corners, like so:

```
+---------|---------|---------------+
| Testing | Column  | Corners       |
+=========|=========|===============+
| Cell    | Corners | Are Not '+'es |
+---------|---------|---------------+
```

**Comment by dhruvasagar** [comment]
@eliedrian This is by design, the reason is since `ftplugin/markdown_tablemode.vim` overrides `let b:table_mode_corner='|'` and that is used instead of the global value. If you want to override this, you should create a `after/ftplugin/markdown/tablemode_override.vim` and set `b:table_mode_corner` to whatever value you wish to.
