### ISSUE TITLE
Formula functionality buggy

### ISSUE THREAD

**Issue by animetrics** [dhruvasagar/vim-table-mode#56]
Hi,

I love this plugin however I've had some apparent buggy behavior with formulas.  Cell references randomly appear not to work properly.  It's hard to nail down a simple example to reproduce the problem since it's random but below is example:

     |---+----------+----------+-------+---------+----------|
     | X | 1        | 1        | R     | R       | R        |
     |---+----------+----------+-------+---------+----------|
     | S | 85000.00 | 7083.33  | 60000 | 5000    |          |
     | S | 15000.00 | 1250.00  | 11250 | 9375    | 1041.665 |
     | S | 31200.00 | 2496.00  | 24600 | 2049.60 |          |
     | S | 10350.00 | 8625.00  | 77000 | 6416.66 |          |
     |---+----------+----------+-------+---------+----------|
     | T |          | 17245.99 |       |         |          |
     |---+----------+----------+-------+---------+----------|
     /* tmf: $5,3=Sum(1,3:3,3)+$4,5; $1,6=($1,3-$1,5)/2 */

The cell references for the first formula work fine.  However, you can see that the result for the second formula appears in cell $2,6 instead of $1,6.  Am I using it wrong?

**Comment by dhruvasagar** [comment]
Hi,

The problem was subtle, thanks for reporting the issue. The problem happened only when there are borders inside the table. Earlier I was using a formula to get the line number of the desired row which doesn't work if we have borders within the table (the header border is fine, but others caused this issue, the one before the last line in your case). I have fixed this issue now.

**Comment by animetrics** [comment]
Great! Thank you.
