### ISSUE TITLE
Unknown function: tablemode#logger#log

### ISSUE THREAD

**Issue by chishaku** [dhruvasagar/vim-table-mode#59]
Installed by copying relevant files to respective directories in ~/.vim.

On osx 10.10, vim 7.3.

Error detected while processing function tablemode#Toggle..<SNR>46_SetActive..<SNR>46_ToggleSyntax..tablemode#SyntaxEnable:
line    1:
E117: Unknown function: tablemode#table#StartExpr
E15: Invalid expression: '/' . tablemode#table#StartExpr() . '\zs|.\+|\ze' . tablemode#table#EndExpr() . '/' 'contains=TableBorder,Ta
bleSeparator,TableColumnAlign containedin=ALL'
Error detected while processing User Auto commands for "TableModeEnabled":
E117: Unknown function: tablemode#logger#log

**Comment by chishaku** [comment]
I didn't copy the whole autoload folder to ~/.vim/autoload.

The README says this:

Copy autoload/tablemode.vim, ... to respective ~/.vim/autoload/,  ...

should be:

Copy autoload/*, ... to respective ~/.vim/autoload/,  ...

**Comment by dhruvasagar** [comment]
Hi, sorry, I think that needs to be updated in the readme, you'll have to copy the entire `autoload` directory and not just that file for table mode to work.

I strongly recommend using a Plugin Manager like Pathogen / Vundle / NeoBundle however, because it will make your life of managing the plugins a lot more easier so you could update them / remove them whenever needed.

**Comment by dhruvasagar** [comment]
Updated the docs, thanks!
