### ISSUE TITLE
fixed columns, wrap in cell

### ISSUE THREAD

**Issue by marmalodak** [dhruvasagar/vim-table-mode#62]
I adore this plugin.

You commented in this question: http://vi.stackexchange.com/a/392/532

With textwidth and formatoptions and wrapmargin, I have failed at limiting the line length.  Should I do something else instead.

Is there any way I could achieve the effect of wrapping in a cell and limit the maximum length of a line?

**Comment by dhruvasagar** [comment]
I am glad you like it.

If I understand you correctly, you essentially want to be able to easily wrap the content just within the third column !?

I am afraid that's something you'd have to probably do by hand. You can always hit `<Enter>` and then type `| | |continuing the third column|` and it will work like you'd expect. Note the spaces between `|` that is important otherwise it would just create a border.

I might have a look into it though and see if I can do something about it, like maybe a mapping like `<C-Enter>` to kind of add a new row and continue typing in the same column.

I have been wanting to add more features of extending the table as well, like moving columns or adding columns.

**Comment by marmalodak** [comment]
I just tried it and it does work well enough for me.

The flexibility of a full-size GUI spreadsheet is what I want.  Oh, I do not need a mouse and can use vim keybindings and plugins  :-)  

Thanks for the tip.

**Comment by dhruvasagar** [comment]
Anytime, I am glad you worked it out.

**Comment by dhruvasagar** [comment]
Anytime, I am glad you worked it out.

**Comment by dhruvasagar** [comment]
Anytime, I am glad you worked it out.
