### ISSUE TITLE
using <Leader>t.. conflicts with command t

### ISSUE THREAD

**Issue by maxcan** [dhruvasagar/vim-table-mode#8]
I know a lot of people (myself included) have <Leader>t mapped to command-t.  it would be nice if VTM allowed for choosing a prefix besides t.

**Comment by codeHatcher** [comment]
what do we add to vim to set the prefix? I see it's table_mode_mappings_prefix but that isn't working for me.

also, I think a lot of people use <leader> - t for command-t. Although I get that since you are tableize you want to be leader t there are still a bunch more people using command-t vs tableize which may deter some users. Just a thought.

**Comment by dhruvasagar** [comment]
@codeHatcher it's `g:table_mode_map_prefix` that should do it for you. Let me know if it doesn't work, i'll have a look if something's wrong.
