### ISSUE TITLE
Support for table headers

### ISSUE THREAD

**Issue by zagy** [dhruvasagar/vim-table-mode#9]
Hi,

vim-table-mode works like charm mostly.

Here's an enhancement suggestion: Support for (rest) table headers.

They're indicated by = instead of -, see http://docutils.sourceforge.net/docs/user/rst/quickref.html#tables

Thanks.

**Comment by jsivak** [comment]
Thanks, that works perfectly.

**Comment by Makistos** [comment]
I can't seem to understand how to create the header. I defined g:table_mode_header_fillchar to '=', typed +- on the first line and defined a header but it doesn't get realigned, or alternatively, it is realigned, but no extra '=' chars are added (i.e. the supposed header is treated like a normal row). I also can't figure out how to defined alignment for columns, adding the colon character to the header line doesn't seem to do anything. Finally, is there a specific bottom row definition?

**Comment by dhruvasagar** [comment]
Hi, in order to add a border you just have type `||` on a new line, if this is in an already existing table it will align accordingly however if it's for starting a new table it will just add something like `|-+-|` but then once you go and add the first row to your table the border will be adjusted automatically. Also as you type / change the table things will be automatically adjusted along the way so you never really have to readjust them ever.

As far as realigning columns, you just have to add the `:` character on the border just after the header on the respective column you need it on. Add it at the beginning just after the `|` or `+` (depending on whether this is the first column or not) so it will look something like `+:------|` to left align or just before the ending `|` or `+` (depending on whether this is the last column or not) so it will look something like this `+----:+` to right align the values in that column.

Now as far as alignment goes the values in the table will align as you either change the table in any way (add a row, change a row, etc), so it won't get triggered right away most likely, however you can always trigger a `:TableModeRealign` or use the mapping `<Leader>tr` to force the table to realign itself at any point in time, the only constraint is that the cursor should be inside the table.

Now there is no specific bottom row as such, the table mode is built in such a way that only the first border right after the first row is treated special by regarding it the header border, besides that you should feel free to add as many or as few borders anywhere else in the table and it shouldn't impact table mode at all, the line numbers & formulas will ignore / skip those additional borders automatically.

**Comment by Makistos** [comment]
Thanks! Got it working now.

**Comment by dhruvasagar** [comment]
@Makistos Just add the header right after the first row, it might appear as |---| at first because of an issue with recognizing it as the header when the cursor is at that position, however post that any changes to the table or by using `:TableModeRealign` /  `<Leader>tr` will redraw the header border correctly using the `g:table_mode_header_fillchar`.

**Comment by Makistos** [comment]
Still can't figure it out, sorry.

Do I start with a normal row (single |), create that and then add the line with (double |)? Doesn't work.

Or do I first create the line (double ||) and then add  a row (single |)? Doesn't work either.

**Comment by dhruvasagar** [comment]
This is how it should look 

```
| This | is | a       | header |
|======+====+=========+========|
| This | is | a       | row    |
| this | is | another | row    |
```

You can invoke `:TableModeRealign` or `<Leader>tr` to realign the table and that will fix the header in case it isn't.

**Comment by Makistos** [comment]
Ah, I have to have a header row on top, it can't be just the line.

**Comment by dhruvasagar** [comment]
Yes there needs to be a header, it doesn't make much sense without it.
